import React from "react";

function Terms() {
  return (
    <div style={styles.page} id="terms">
      <div style={styles.card}>
        <h1 style={styles.title}>Terms & Conditions</h1>

        <h3>Usage Terms</h3>
        <p style={styles.text}>
          By accessing this platform, you agree to the following terms.
        </p>

        <h3>Acceptable Use</h3>
        <p style={styles.text}>You agree not to use this service for:</p>
        <ul style={styles.list}>
          <li>Illegal content generation</li>
          <li>Harmful or abusive text</li>
          <li>Misuse of system resources</li>
        </ul>

        <h3>Service Availability</h3>
        <p style={styles.text}>
          We do not guarantee uninterrupted availability and reserve the right to modify or suspend the service at any time.
        </p>

        <h3>Accuracy Disclaimer</h3>
        <p style={styles.text}>
          While we strive for high accuracy, results are generated by an AI model and may not always be perfect.
        </p>

        <h3>Intellectual Property</h3>
        <p style={styles.text}>
          All system components, models, and website content are owned by the platform unless otherwise stated.
        </p>
      </div>
    </div>
  );
}

export default Terms;

const styles = {
  page: {
    minHeight: "100vh",
    background: "linear-gradient(135deg, #667eea, #ffffff)",

    // ✅ IMPORTANT FIX for header overlap
    padding: "90px 40px 40px",

    display: "flex",
    justifyContent: "center",
    alignItems: "flex-start", // better than center for long pages
  },

  card: {
    maxWidth: "800px",
    padding: "30px 40px",
    background: "transparent",
    boxShadow: "none",
  },

  title: {
    fontSize: "28px",   // smaller
    marginBottom: "20px",
    fontWeight: "700",
    color: "#1a1a1a",
  },

  subtitle: {
    marginTop: "20px",
    fontSize: "18px",   // smaller
    fontWeight: "600",
    color: "#222",
  },

  text: {
    fontSize: "15px",   // smaller text
    lineHeight: "1.8",
    marginBottom: "12px",
    color: "#2b2b2b",
  },
};